/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ceramica;

/**
 *
 * @author alber
 */
public class Calculador extends javax.swing.JFrame {

    /**
     * Creates new form Calculador
     */
    public Calculador() {
        initComponents();
        hide();
    }
    public void hide() {
        jLabel10.hide();
    }

    public static boolean esArcillaRoja(double siO2, double al2o3, double fe2o3, double cao, double mgo, double na2o, double k2o, double tio2, double ppc) {
        return (fe2o3 > 3.5 && fe2o3 < 8) &&
               (siO2 > 30 && siO2 < 65) &&
               (al2o3 > 12 && al2o3 < 25) &&
               (mgo > 0.8 && mgo < 3) &&
               (na2o > 0.1 && na2o < 0.9) &&
               (k2o > 3 && k2o < 5) &&
               (tio2 < 1.2) &&
               ((cao > 0.5 && cao < 2) || (cao > 2 && cao < 5) || (cao > 10 && cao < 25)) &&
               ((ppc > 15 && ppc < 23) || (ppc > 7 && ppc < 10) || (ppc < 6));
    }

    public static boolean esArcillaBlanca(double siO2, double al2o3, double fe2o3, double cao, double mgo, double na2o, double k2o, double tio2, double ppc) {
        return (fe2o3 > 0.8 && fe2o3 < 5) &&
               (siO2 > 48 && siO2 < 79) &&
               (al2o3 > 15 && al2o3 < 35) &&
               (mgo < 0.8) &&
               (na2o > 0.1 && na2o < 1) &&
               (k2o > 0.7 && k2o < 3.5) &&
               (tio2 > 0.9 && tio2 < 2) &&
               (cao < 0.9) &&
               (ppc > 3.5 && ppc < 12);
    }

    public static boolean esCaolin(double siO2, double al2o3, double fe2o3, double cao, double mgo, double na2o, double k2o, double tio2, double ppc) {
        return (fe2o3 > 0.3 && fe2o3 < 2) &&
               (siO2 > 45 && siO2 < 60) &&
               (al2o3 > 25 && al2o3 < 38) &&
               (mgo < 0.4) &&
               (na2o > 0.04 && na2o < 0.8) &&
               (k2o > 0.5 && k2o < 2.5) &&
               (tio2 < 0.5) &&
               (cao > 0.02 && cao < 0.22) &&
               (ppc > 8 && ppc < 13.6);
    }

    public static boolean esArenaFeldespatica(double siO2, double al2o3, double fe2o3, double cao, double mgo, double na2o, double k2o, double tio2, double ppc) {
        return (fe2o3 > 0.05 && fe2o3 < 0.15) &&
               (siO2 > 80 && siO2 < 97) &&
               (al2o3 > 2 && al2o3 < 11) &&
               (mgo < 0.2) &&
               (na2o > 0.1 && na2o < 0.6) &&
               (k2o > 1 && k2o < 4) &&
               (tio2 < 0.03) &&
               (cao < 0.08) &&
               (ppc < 2);
    }

    public static boolean esCarbonato(double siO2, double al2o3, double fe2o3, double cao, double mgo, double ppc) {
        return ((cao > 50 && cao < 56) && (mgo < 2.5) && (ppc > 40 && ppc < 45) && (siO2 < 3) && (al2o3 < 1)) ||
               ((cao > 30) && (mgo > 20) && (ppc > 45) && (siO2 < 0.5) && (al2o3 < 1)) ||
               ((cao > 0.1 && cao < 3) && (mgo > 90) && (ppc < 1) && (siO2 < 3) && (al2o3 < 1));
    }

    public static boolean esTalco(double siO2, double al2o3, double fe2o3, double cao, double mgo, double ppc) {
        return (fe2o3 > 0.6 && fe2o3 < 2) &&
               (siO2 > 45 && siO2 < 62) &&
               (al2o3 > 0.5 && al2o3 < 10) &&
               (mgo > 25 && mgo < 35) &&
               (cao > 0.5 && cao < 2) &&
               (ppc > 7 && ppc < 9);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setPreferredSize(new java.awt.Dimension(64, 22));
        jTextField1.setRequestFocusEnabled(false);

        jTextField2.setPreferredSize(new java.awt.Dimension(64, 22));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setPreferredSize(new java.awt.Dimension(64, 22));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setPreferredSize(new java.awt.Dimension(64, 22));

        jTextField5.setPreferredSize(new java.awt.Dimension(64, 22));

        jTextField6.setPreferredSize(new java.awt.Dimension(64, 22));

        jTextField7.setPreferredSize(new java.awt.Dimension(64, 22));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.setPreferredSize(new java.awt.Dimension(64, 22));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.setPreferredSize(new java.awt.Dimension(64, 22));

        jButton1.setText("Comprobar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("SiO2");

        jLabel2.setText("Fe203");

        jLabel3.setText("Al203");

        jLabel4.setText("Ca0");

        jLabel5.setText("Mg0");

        jLabel6.setText("Na20");

        jLabel7.setText("K20");

        jLabel8.setText("Ti02");

        jLabel9.setText("PPC");

        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel10)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(44, 44, 44)
                .addComponent(jLabel10)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    try {
            double siO2 = Double.parseDouble(jTextField1.getText());
            double al2o3 = Double.parseDouble(jTextField2.getText());
            double fe2o3 = Double.parseDouble(jTextField3.getText());
            double cao = Double.parseDouble(jTextField4.getText());
            double mgo = Double.parseDouble(jTextField5.getText());
            double na2o = Double.parseDouble(jTextField6.getText());
            double k2o = Double.parseDouble(jTextField7.getText());
            double tio2 = Double.parseDouble(jTextField8.getText());
            double ppc = Double.parseDouble(jTextField9.getText());
            jLabel10.show();
            CheckMarronEste(siO2, al2o3, fe2o3, cao, mgo, na2o, k2o, tio2, ppc); 
            
            
        } catch (NumberFormatException e) {
            jLabel10.show();
            jLabel10.setText("Un campo no contiene un numero");
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    public void CheckMarronEste(double siO2, double al2o3, double fe2o3, double cao, double mgo, double na2o, double k2o, double tio2, double ppc) {
        if (esArcillaRoja(siO2, al2o3, fe2o3, cao, mgo, na2o, k2o, tio2, ppc)) {
            jLabel10.setText("Es arcilla Roja");
        } else if (esArcillaBlanca(siO2, al2o3, fe2o3, cao, mgo, na2o, k2o, tio2, ppc)) {
            jLabel10.setText("Es arcilla Blanca");
        } else if (esCaolin(siO2, al2o3, fe2o3, cao, mgo, na2o, k2o, tio2, ppc)) {
            jLabel10.setText("Es Caolin");
        } else if (esArenaFeldespatica(siO2, al2o3, fe2o3, cao, mgo, na2o, k2o, tio2, ppc)) {
            jLabel10.setText("Es Arena Feldespatica");
        } else if (esCarbonato( siO2,  al2o3,  fe2o3,  cao,  mgo,  ppc)) {
            jLabel10.setText("Es Carbonato");
        } else if (esTalco( siO2,  al2o3,  fe2o3,  cao,  mgo,  ppc)) {
            jLabel10.setText("Es Talco");
        } else {
            jLabel10.setText("No es un valor valido");
        }
    }
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
